# Generated by Django 5.0.4 on 2024-05-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_sheet',
            field=models.IntegerField(blank=True, null=True, verbose_name='enter your book_sheet'),
        ),
        migrations.AddField(
            model_name='manager',
            name='family',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='enter your family'),
        ),
        migrations.AddField(
            model_name='manager',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='enter your phone number'),
        ),
        migrations.AddField(
            model_name='moderator',
            name='family',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='enter your family'),
        ),
        migrations.AddField(
            model_name='moderator',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='enter your phone number'),
        ),
        migrations.AddField(
            model_name='schools',
            name='addres',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='enter your schools addres'),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='enter your age'),
        ),
        migrations.AddField(
            model_name='student',
            name='family',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='enter your family'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='enter your phone number'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schools',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='enter your name'),
        ),
    ]
