# Generated by Django 5.0.4 on 2024-05-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_student_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='name',
            new_name='manager_name',
        ),
    ]
