# Generated by Django 5.0.4 on 2024-05-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_rename_name_manager_manager_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='supervisors',
            new_name='Moderator',
        ),
    ]
