# Generated by Django 5.0.4 on 2024-05-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_remove_schools_moderator_moderator_schools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_lesson',
            name='school',
        ),
        migrations.AddField(
            model_name='schools',
            name='class_Lesson',
            field=models.ManyToManyField(blank=True, null=True, to='schools.class_lesson'),
        ),
    ]
