# Generated by Django 5.0.4 on 2024-05-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_remove_class_lesson_school_schools_class_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.ManyToManyField(limit_choices_to=9, to='schools.book'),
        ),
    ]
