# Generated by Django 5.0.4 on 2024-05-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_alter_student_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='class_Lesson',
            field=models.ManyToManyField(blank=True, to='schools.class_lesson'),
        ),
    ]
