# Generated by Django 5.0.4 on 2024-05-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_book_book_sheet_manager_family_manager_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.ManyToManyField(limit_choices_to=10, to='schools.book'),
        ),
    ]
