# Generated by Django 5.0.4 on 2024-05-09 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_rename_supervisors_schools_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='Moderator',
        ),
        migrations.AddField(
            model_name='schools',
            name='Moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.moderator'),
        ),
    ]
