# Generated by Django 5.0.4 on 2024-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_alter_schools_class_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.ManyToManyField(editable=10, to='schools.book'),
        ),
    ]
