# Generated by Django 5.0.4 on 2024-05-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_alter_student_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='enter your title'),
        ),
    ]
