# Generated by Django 5.0.4 on 2024-05-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_alter_class_lesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.ManyToManyField(limit_choices_to={'id__lte': 10}, to='schools.book'),
        ),
    ]
