# Generated by Django 5.0.4 on 2024-05-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='enter your name')),
                ('family', models.CharField(max_length=25, verbose_name='enter your family')),
                ('phone', models.CharField(max_length=11, verbose_name='enter your phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='enter your title', max_length=25)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Condition', models.CharField(choices=[('True', 'خوانده شده'), ('False', 'خوانده نشده')], default=False, max_length=9)),
                ('Ticket_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.users')),
            ],
        ),
    ]
