# Generated by Django 5.0.4 on 2024-05-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_group_person_membership_group_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
