# Generated by Django 5.0.4 on 2024-05-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_delete_group_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=25, verbose_name='enter your title'),
        ),
    ]
