name: Deploy Django Code Only

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
        host: organization.itols.ir
          username: itolsir          
          key: |
            
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAgEArQztt+uf0cQev5KG53dYzAQMiFECwpqhW5bSBPPyljyB0WQFnQ4j
            Hvat3Isb183IiGLXESisrskBDUYmR+AuRKPQgrpG5N04/8BY5KRDaMK1lzGKunz0uCCNcB
            s7EhKE56fRojCBYRRBEZl/AQMZ3ubKxaIIPck9BuwFz8NnaKDNFDeoqj7eO9TJMd8qgcSK
            fS6AOWcK09yolzqFlyNbrI7sk+0KEe2yr7TsYqYC/H5s4KunybWcv+83Jg4Y+Y3E11eJQp
            ARkQq9VRYZ0395k3sTVgWirRwjBFBASc6uviYQXnydDh2cq0pg+Mu2ha+WfJAMcRfX3SaO
            +XJ8lO7YMweqa+b1Ul/oqw4HAyDgfVhawxkKydK8k4Wdrwrs+bn0/qxsuh/jfuJ4qQoUnC
            8q/VB6uCPGgHn7u/Ygjw1rXEkJi1Hfa5wMeXfTLZi0cGwZKeEGuuGXx6ds+OS/I1+vOvtK
            DeVuIERfHwe+EbqrpTPweVhsZ8rK94s7GHBSPoSXDngAc+sYQygBZHUzdkbawy/8XOCQqZ
            asB+OCpSBSpoVZfUjh9T01mEsnyt8iC2axCAMtRtnG6WQ8LsuY+DbbaAbeh+aE6bBMC0wa
            rh8yk9dCFHNVsCHEng3WcGObnjl3zSFmKcyCuXS3yRpfyM+2tTcnwmPMQhL5hG+g5/HvqC
            EAAAdAUzcwTVM3ME0AAAAHc3NoLXJzYQAAAgEArQztt+uf0cQev5KG53dYzAQMiFECwpqh
            W5bSBPPyljyB0WQFnQ4jHvat3Isb183IiGLXESisrskBDUYmR+AuRKPQgrpG5N04/8BY5K
            RDaMK1lzGKunz0uCCNcBs7EhKE56fRojCBYRRBEZl/AQMZ3ubKxaIIPck9BuwFz8NnaKDN
            FDeoqj7eO9TJMd8qgcSKfS6AOWcK09yolzqFlyNbrI7sk+0KEe2yr7TsYqYC/H5s4Kunyb
            Wcv+83Jg4Y+Y3E11eJQpARkQq9VRYZ0395k3sTVgWirRwjBFBASc6uviYQXnydDh2cq0pg
            +Mu2ha+WfJAMcRfX3SaO+XJ8lO7YMweqa+b1Ul/oqw4HAyDgfVhawxkKydK8k4Wdrwrs+b
            n0/qxsuh/jfuJ4qQoUnC8q/VB6uCPGgHn7u/Ygjw1rXEkJi1Hfa5wMeXfTLZi0cGwZKeEG
            uuGXx6ds+OS/I1+vOvtKDeVuIERfHwe+EbqrpTPweVhsZ8rK94s7GHBSPoSXDngAc+sYQy
            gBZHUzdkbawy/8XOCQqZasB+OCpSBSpoVZfUjh9T01mEsnyt8iC2axCAMtRtnG6WQ8LsuY
            +DbbaAbeh+aE6bBMC0warh8yk9dCFHNVsCHEng3WcGObnjl3zSFmKcyCuXS3yRpfyM+2tT
            cnwmPMQhL5hG+g5/HvqCEAAAADAQABAAACACpOBlFXp3b7CH9R3Wv5p7ocZUnv8ApODhNb
            cBVo482plhzv5FVsTtazfHZ1hYWA17zL2QLnXCvQlNK/av1YR0ddesxyqIErudMAHVsr8x
            TJwOXo5R7JDHR09M7KwWqeH2KYiq2pSP/IGU4ppbxEG098QWcGQRiFuUcXbSZJAV85LFl8
            b93Kx759uv/XrEcUGr0WoJ8n2yRHBeoOkvkLWk55lElngfY3E19UDhPhvMooSAq2vCqaHO
            tpGiTR/nYHm+7/Bd3BZaH9K6MA56hmOfz9chEuCIJkZgUYb1b70YlHuem3chew0ounf8Ri
            3Miaz+G8v2Xoa8uzMPG3dNBeAXk0be1vmL4v7JmKt9wyL5+LRknz+v52Isi7Vi41PpbFOc
            ftgywrXKFoZLfe7eV+EISx7cvEeHOrinrbbjgzs7HUkx1WYUIIsDAD1DQR7A9K9WLXTEI7
            MyarZOLn4yIOzQORQvjLEbeUaep6NMzzIPwIpknawmbGfEJP/lpl681IVJV2i+8gcDbnTt
            YoPZG4VONR8HYkAICGBG6fyEBFOuWkQBRCOnH75A/oy9ZT0VsJ+SHg10mKAZ3ah2Mxewb6
            irtyCM7QuUaLgyHSrngEYUYwBpVVAi9mz1SWDR0nzcn6tIGn9RRwL/w+9KaJvQzxxBeffD
            jTXdA8e62+EbYFW7qXAAABAAmCtOlgZw/FKYbZG+JNQmaJsbRZ1Qa3unfBEeUKpD81UYyT
            aGh5/eBV5y55ETyWB5/Abq6IrG6jx0WRdK75fKWHBTnGUgUJ8HO0b6anMaV79iJZm7tJPu
            7NVCg0RxAw1LmtSuavdF5D1pZP5MIn2U0dDtYdYAgYCUSdt53dFGkIA+aGX0zyWe+sPr4l
            dIEcUmBRoX9kWsw21/XXL/+mtr77tpsl2SJMLE6RGtQY/VQx5vdrpbKarGC76jgaRH2xtF
            9rVkbyi+w8KhMeI2WCagnIBn2B6ZWLgKx2BIY9mzzC6miEzgGR7uUvv9W+E1kZqNvTbfUZ
            3nynxlcz25MUppgAAAEBAO82pu0RWoZ1Wby0pHQ6Dr25Nf4piciiAPBDv0gz9V39MJODUe
            qFEGOQvlvQlPofhIvphqN7/0eks1Ahgt3+X8rTmI4EPRmUENNoEDWwtOVcRu8eox1JApHz
            Ax0AovcmR2V1qHT/CqhlQY95bKJYAruTHUnnSj1AWuBOsJihLKG8xBiGO97tRgYPB51zla
            WEOEkvRePBI/ME0j9F0LdHshdebxXfz3gcXqdxLjTU3l3CkTtX1ZxPDACKR6WZ3Smx9Q80
            GCrUvZepa8hX8/T6+bQPupVrLl7YTAox5lXrwaXLcrNrQ47Hl06qfN6zA80J8vPJaf4n3S
            hHYDajIkqIb7cAAAEBALkxsUA

          port: 22
          script: |
            echo "Deploy started on $(date)"
            source /home/itolsir/virtualenv/organization.itols.ir/3.11/bin/activate && cd /home/itolsir/organization.itols.ir
            git fetch origin
            git reset --hard origin/main
            echo "Deploy finished on $(date)"
