name: Django Auto Deploy

on:
  push:
    branches:
      - main  # یا master اگر برنچ اصلی master است

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ checkout کد
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ اتصال به هاست و اجرای دستورات
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          echo "Deploy started on $(date)"
          
          # مسیر پروژه Django
          cd /home/itolsir/organization.itols.ir
          
          # pull آخرین تغییرات
          git fetch origin
          git reset --hard origin/main
          
          # فعال کردن virtualenv (فرض می‌کنیم در مسیر venv هست)
          source /home/itolsir/organization.itols.ir/venv/bin/activate
          
          # نصب dependencies
          pip install -r requirements.txt
          
          # migrate دیتابیس
          python manage.py migrate
          
          # collectstatic
          python manage.py collectstatic --noinput
          
          # restart پروژه (بسته به سرور شما: systemd, gunicorn, uwsgi یا cPanel)
          # اگر با cPanel و Passenger است:
          touch tmp/restart.txt
          
          echo "Deploy finished on $(date)"
