name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
jobs:
  build-and-deploy:
    runs-on: cpanel-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy frontend to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/itolsir/itols/frontend
          git pull origin main
          npm install
          npm run build
          rm -rf /home/itolsir/public_html/*
          cp -r build/* /home/itolsir/public_html/