name: Deploy Django Code Only

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: organization.itols.ir
          username: itolsir
          key: ${{ secrets.SSH_KEY}}
          script: |
            echo "Deploy started on $(date)"
            source /home/itolsir/virtualenv/organization.itols.ir/3.11/bin/activate
            cd /home/itolsir/organization.itols.ir
            git fetch origin
            git reset --hard origin/main
            echo "Deploy finished on $(date)"
